from app.v1.user.user_route import user_bp
from app.v1.auth.auth_route import auth_bp
from app.v1.contact_us.contact_us_route import contact_us_bp
from app.v1.team.team_route import team_bp
from app.v1.plan.plan_route import plan_bp
from app.v1.record.record_route import record_bp
from app.v1.archer_rank.archer_rank_route import archer_rank_bp
from app.v1.subscription.subscription_route import subscription_bp
from app.v1.paystack.paystack_route import payment_bp
from app.v1.history.payment_history_route import payment_history_bp
from app.v1.champion_user.champion_user_route import champion_user_bp
from app.v1.file_upload.file_upload_route import file_upload_bp